import streamlit as st
import base64
from src.graph import eval_app

def get_image_base64(uploaded_file):
    """Encodes the uploaded Streamlit file into base64."""
    uploaded_file.seek(0) # Reset file pointer in case it was read by st.image()
    bytes_data = uploaded_file.read()
    return base64.b64encode(bytes_data).decode('utf-8')

# Ensure Streamlit state variables are initialized
if 'eval_result' not in st.session_state:
    st.session_state.eval_result = None
if 'mcq_submitted' not in st.session_state:
    st.session_state.mcq_submitted = False
if 'user_answers' not in st.session_state:
    st.session_state.user_answers = {}

st.set_page_config(page_title="Sys Design Workshop Engine", layout="centered")

st.title("🧩 System Design Workshop Evaluator")
st.markdown("Automated evaluation engine using Multi-Agent LLMs.")

# STEP 1: UPLOAD DESIGN
if st.session_state.eval_result is None:
    st.header("Step 1: Submit Your Design Phase")
    
    team_id = st.text_input("Team ID")
    problem = st.text_area("System Design Problem Statement", height=150)
    image = st.file_uploader("Upload System Design Diagram", type=["png", "jpg", "jpeg"])
    
    if image is not None:
        st.success("✅ Image successfully uploaded!")
        with st.expander("👁️ View Uploaded Diagram"):
            st.image(image, caption="System Design to be Evaluated", use_container_width=True)
    
    if st.button("Submit Design for Evaluation", type="primary"):
        if team_id and problem and image:
            with st.spinner("AI Agents are actively analyzing Architecture, Grading, and Generating Edge Cases. Please wait..."):
                b64_img = get_image_base64(image)
                
                # Mock Initial State
                state = {
                    "team_id": team_id,
                    "sd_problem": problem,
                    "image_b64": b64_img,
                    "extracted_design": "",
                    "score_80": 0,
                    "evaluator_feedback": "",
                    "edge_cases": [],
                    "mcqs": []
                }
                
                # Run the Pipeline
                try:
                    result = eval_app.invoke(state)
                    st.session_state.eval_result = result
                    st.rerun() # Refresh to jump to Step 2
                except Exception as e:
                    st.error(f"Pipeline Execution Failed: {e}")
        else:
            st.warning("Please fill out all inputs before submitting.")

# STEP 2: ANSWER MCQS GENERATED DYNAMICALLY
elif not st.session_state.mcq_submitted:
    st.header(f"Step 2: Edge Case Scenario Questions (Team: {st.session_state.eval_result['team_id']})")
    st.info("The architectural evaluation is complete. based on edge cases found in your design, please answer the following scenarios to accumulate your remaining 20 points.")
    
    questions = st.session_state.eval_result.get("mcqs", [])
    
    if not questions:
        st.error("No questions were generated by the AI. Review model outputs.")
        if st.button("Reset"):
            st.session_state.clear()
            st.rerun()
    else:
        with st.form("mcq_form"):
            for i, q in enumerate(questions):
                st.write(f"**Q{i+1}: {q.get('question', 'Missing Question Text')}**")
                options = q.get('options', [])
                
                # We add a default non-option so users are forced to choose
                display_options = ["Select an option..."] + options 
                
                selected = st.radio(f"Options for Q{i}", display_options, key=f"ans_{i}", label_visibility="collapsed")
                st.session_state.user_answers[i] = selected
                st.markdown("---")
            
            submit_answers = st.form_submit_button("Submit Answers & Reveal Final Score")
            if submit_answers:
                # Check if all questions are answered
                unanswered = [i for i in range(len(questions)) if st.session_state.user_answers[i] == "Select an option..."]
                if unanswered:
                    st.warning("Please answer all questions before submitting.")
                else:
                    st.session_state.mcq_submitted = True
                    st.rerun()

# STEP 3: REVEAL FINAL SCORE & BREAKDOWN
else:
    st.header("Step 3: Final Evaluation & Report")
    
    result = st.session_state.eval_result
    questions = result.get("mcqs", [])
    
    # Calculate MCQ Score
    mcq_score = 0
    for i, q in enumerate(questions):
        if st.session_state.user_answers.get(i) == q.get("correct_answer"):
            mcq_score += 1
            
    base_score = result.get("score_80", 0)
    final_score = base_score + mcq_score
    
    st.success(f"## Final Team Score: {final_score} / 100")
    
    # Visual Metrics
    col1, col2 = st.columns(2)
    with col1:
        st.metric("System Design Evaluation", f"{base_score} / 80")
    with col2:
        st.metric("Edge Case Handling", f"{mcq_score} / 20")
        
    st.markdown("---")
    
    # Show Original Feedback
    st.subheader("Architectural Feedback")
    st.write(result.get("evaluator_feedback", "No feedback provided by Agent 2."))
    
    st.subheader("Identified Architecture Edge Cases:")
    for ec in result.get("edge_cases", []):
        st.markdown(f"- {ec}")
        
    st.markdown("---")
    
    # MCQ Review
    st.subheader("MCQ Review")
    for i, q in enumerate(questions):
        correct_ans = q.get("correct_answer")
        user_ans = st.session_state.user_answers.get(i)
        is_correct = (user_ans == correct_ans)
        
        icon = "✅" if is_correct else "❌"
        
        with st.expander(f"Q{i+1}: {q.get('question')} {icon}"):
            st.write(f"**Your Answer:** {user_ans}")
            st.write(f"**Correct Answer:** {correct_ans}")
            if not is_correct:
                st.info(f"**Explanation:** {q.get('explanation')}")
            else:
                st.success(f"**Explanation:** {q.get('explanation')}")

    if st.button("Evaluate Another Team"):
        st.session_state.clear()
        st.rerun()
